### ISSUE TITLE
write deleting servlets

### ISSUE THREAD

**Issue by vashli** [ilakli/MACS-classroom#26]
1. RemoveSeminaristFromSeminarServlet (parameters: classroomID, seminarN)
2. RemoveStudentsFromSeminarServlet(parameters: classroomID, seminarN, studentsEmails)
3. RemoveSectionLeaderFromSectionServlet(parameters: classroomID, sectionN)
4. RemoveStudentsFromSectionServlet(parameters: classroomID, sectionN, studentsEmails)

**Comment by vashli** [comment]
seminarN and sectionN parameters are not necessary

**Comment by ilakli** [comment]
done
