### ISSUE TITLE
Sending emails when someone added post, graded homework ...

### ISSUE THREAD

**Issue by cxovrika** [ilakli/MACS-classroom#34]

**Comment by xosrika** [comment]
ADDED EMAILS FOR:
1. adding post(sending to everyone but sender)
2. studentassignment.jsp adding comment. sending to section leader, seminarist, student (but not sender);
3. creating classroom - sending to creator;
4. studentassignment.jsp while giving grade, sending only student;
I will keep testing them and push them after a hour, write if there is needed more;

**Comment by xosrika** [comment]
Added emails when new assignment was added;
Had bug when there was no email to send text.

**Comment by xosrika** [comment]
Done
